### ISSUE TITLE
Bug - Ordering of Monitors list is not updating uptime percentages properly 

### ISSUE THREAD

**Issue by Kubik-Rubik** [plesk/ext-uptime-robot#7]
If you you change the sort order of the list by clicking on the "ID" or "URL", then the uptime percentages are not re-loaded. Only after a complete page refresh the values are loaded and displayed in the list.

Actual result:
<img width="1389" alt="bug-ext-uptime-percentages" src="https://user-images.githubusercontent.com/1976103/29209002-9d29f036-7e8c-11e7-8e89-5e79a3766788.png">

Expected result:
<img width="1393" alt="bug-ext-uptime-percentages-correct" src="https://user-images.githubusercontent.com/1976103/29209526-4ffd1362-7e8f-11e7-86dd-feffaa8940ff.png">

**Comment by frankred** [comment]
There were no uptimes attached within the `monitorslistDataAction`. Just fixed it!

**Comment by Kubik-Rubik** [comment]
@frankred Works as expected now. Well done!
